{% set name = "plottr" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 552f1641373380c193e7d4641c4c42718b2a4e0e5d0e1ff44786a452bf34644c

build:
  number: 0
  skip: true  # [py==27]
  skip: true  # [py<=37]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plottr-monitr = plottr.apps.monitr:script
    - plottr-inspectr = plottr.apps.inspectr:script
    - plottr-autoplot-ddh5 = plottr.apps.autoplot:script

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - python
    - pip
    - versioningit
  run:
    - python
    - pandas >=0.22
    - xarray
    - pyqtgraph >=0.12.1
    - matplotlib >=3.0.0
    - numpy >=1.12.0
    - lmfit >=1.0
    - h5py >=2.10.0
    - qtpy >=1.9.0
    - typing_extensions >=3.7.4.3
    - packaging >=20.0
    - xhistogram >=0.3.0
    - versioningit >=1.1.0
  run_constrained:
    - pyside2 >=5.12
    - pyqt

test:
  requires:
    - pyqt
  imports:
    - plottr

about:
  home: https://github.com/toolsforexperiments/plottr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool for live plotting and processing data
  description: |
    A framework for inspecting data, based on flowcharts from pyqtgraph.
    plottr's main aim is to allow the user to define custom data processing flows and plotting.
    A particular use case is data filtering and plotting.
  doc_url: https://plottr.readthedocs.io/en/latest/
  dev_url: https://github.com/toolsforexperiments/plottr

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - trevormorgan
    - astafan8
    - jenshnielsen
    - wpfff
